"""Add GitHub fields to User model

Revision ID: 86ff36e79ccc
Revises: b14b2826551b
Create Date: 2025-07-16 18:27:54.214101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ff36e79ccc'
down_revision = 'b14b2826551b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('github_token', sa.String(length=200), nullable=True))
        # THIS IS THE FIX: Added a name for the unique constraint
        batch_op.create_unique_constraint(batch_op.f('uq_user_github_id'), ['github_id'])
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_user_github_id'), type_='unique')
        batch_op.drop_column('github_token')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###